server:
  port: 8080

mail:
  config:
    local: /data/server/send1_ledao/lookLog/sendStatus2.txt
    sendTopic: 乐到,国标,成都,乐到杭州

spring:
  mail:
    host: smtp.exmail.qq.com
    username: zentao@futuremove.cn
    password: 123456Fm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
