server:
  port: 8009

mail:
  config:
    local: /data/sendLog/sendStatus.txt
    sendTopic: 乐到,国标,成都,西安

spring:
  mail:
    host: smtp.exmail.qq.com
    username: zentao@futuremove.cn
    password: 123456Fm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
